# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build and Test

on: [push, pull_request]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11, 17]

    name: Build and Test(java ${{ matrix.java }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK ${{ matrix.java }}
      id: java_setup
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
        cache: 'maven'

    - name: Build with Maven
      id: build
      run: mvn -B package --file pom.xml

    - name: Upload artifacts
      id: artifacts_upload
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: build-java-${{ matrix.java }}-${{ matrix.os }}
        path: target/tome25s-java-utilities-*.jar
