# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-java-8-ubuntu:
    name: Build and Test(Java 8, Ubuntu)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifacts
      id: artifacts_upload
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: target/ToMe25s-Java-Utilities-*.jar

  test-java-8-windows:
    name: Build and Test(Java 8, Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifacts
      id: artifacts_upload
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: target\ToMe25s-Java-Utilities-*.jar
